schedule_interval: "0 0 * * *"
retry_attempts: 3

kaggle:
  credentials_path: "../.kaggle/kaggle.json"
  dataset: radheshyamkollipara/bank-customer-churn
  raw_data_dir: "./raw_data/kaggle"
  clean_data_dir: "./clean_data/kaggle"
  log_dir: "./logs"
  clean_output_csv: "./clean_data/kaggle/customer_churn.csv"

huggingface:
  url: "https://huggingface.co/datasets/praneeth232/bank-customer-churn/resolve/main/bank_customer_churn.csv"
  raw_data_dir: "./raw_data/huggingface"
  clean_data_dir: "./clean_data/huggingface"
  log_dir: "./logs"
  clean_output_csv: "./clean_data/huggingface/hf_customer_churn_cleaned.csv"

